# 版本信息
version_msg:
    __version__: '1.0.0'
    sbyqbb: BankOCR_v1.1.0
    mbbs: BANK_STANDARD_MODEL
# 数据库信息
database:
    host: 172.23.0.132
    port: 5688
    db_name: ticketsocr
    user: root
    passwd: root123456
    # 所用表名称
    table_name:
        bft: bank_fault_tolerant
        btc: bank_ticket_config_tb
        bcaft: bank_capital_amount_fault_tolerant
# 任务信息
task_msg:
    url:
        # 测试服务器
        # posturl: http://172.23.0.238:8200/scanning/scan/receiveResult
        # geturl: http://172.23.0.238:8200/scanning/scan/getScanTask
        # 开发联调服务器
        geturl: http://172.23.0.238:18100/scanning/scan/getScanTask
        posturl: http://172.23.0.238:18100/scanning/scan/receiveResult
    # 一次最多取的任务量
    taskSize: '15'
    # 任务量池的最大数量（进程间通信）
    maxsize: 20
# 腾讯优图登录信息
tencentYoutu_params:
    appid: '10137338'
    secret_id: AKIDvlRwGRGQ2TjpjV4i9QWRxIi3ZurjmLRO
    secret_key: vfDaAh8PXfcO8j9OSL6g6NWUGrHWZQ6b
    userid: '2926476187'
# 日志文件信息
log_msg:
    # ufile log文件位置及名字 (100代表代码版本1.0.0)
    ufile_log: '../log/ufile_100.log'